feign:
  client:
    config:
      processInstance:
        url: "http://localhost:8083/engine-rest/"
      processDefinition:
        url: "http://localhost:8083/engine-rest/"
      message:
        url: "http://localhost:8083/engine-rest/"
      signal:
        url: "http://localhost:8083/engine-rest/"
      execution:
        url: "http://localhost:8083/engine-rest/"
      task:
        url: "http://localhost:8083/engine-rest/"
      taskVariable:
        url: "http://localhost:8083/engine-rest/"
      taskLocalVariable:
        url: "http://localhost:8083/engine-rest/"
      taskIdentityLink:
        url: "http://localhost:8083/engine-rest/"
      externalTask:
        url: "http://localhost:8083/engine-rest/"
