

[cols="a,a,a,a,a"]
|===
|
image::https://img.shields.io/badge/Community%20Extension-An%20open%20source%20community%20maintained%20project-FF4700[caption="Comuinity Extension", link=https://github.com/camunda-community-hub/community]
|
image::https://img.shields.io/badge/Lifecycle-Deprecated-red[caption="Deprecated", link=https://img.shields.io/badge/Lifecycle-Deprecated-yellowgreen)](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#deprecated-[https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#relocated-]]
|
image::https://img.shields.io/badge/Compatible%20with-Camunda%20Platform%207-26d07c[caption="compatible with Camunda Platform 7"]
| // license
image::https://img.shields.io/badge/License-Apache%202.0-blue.svg[caption="License", link="https://github.com/camunda-community-hub/camunda-platform-7-rest-client-spring-boot/blob/master/LICENSE"]
| // sponsored
image::https://img.shields.io/badge/sponsoredBy-Holisticon-RED.svg[caption="sponsored", link="https://holisticon.de/"]
|===

[CAUTION]
.Discontinued/Moved
====
Due to the end of live of Camunda 7 CE with 7.24, we decided to discontinue this extension and archive the repository.
The Release 7.24.1 will be the last one.

However, we included the *current state* of the extension into the link:https://github.com/holunda-io/c7/[holunda-io/c7] repository, where we will maintain it together with other extensions and keep it working for future C7-EE releases.
====



== Introduction

This library aims to provide a REST client for Camunda REST API for SpringBoot. In doing so it offers "remote" implementations of Camunda
Engine Java API. This project is highly iterative and releases the functionality in small increments. Please check the link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/user-guide/support-matrix.html[support matrix]
to find out if the functionality you require is already supported by the library.

[cols="a,a,a"]
|===
| Library | Spring Boot | Spring Cloud

| 7.24.0 | 3.5.7 | 2025.0.0
| 7.23.5 | 3.5.6 | 2025.0.0
| 7.23.3 | 3.4.5 | 2024.0.1
| 7.23.2 | 3.4.5 | 2024.0.1
| 7.23.1 | 3.4.5 | 2024.0.1
| 7.23.0 | 3.4.5 | 2024.0.1
| 7.22.4 | 3.4.3 | 2024.0.1
| 7.22.3 | 3.4.2 | 2024.0.0
| 7.22.2 | 3.4.2 | 2024.0.0

|===


== Quick Start

If you just want to start using the library, please consult our link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/getting-started.html[Quick Start]
guide.

== Working Example

We provide a working example demonstrating some features of the library. See our link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/user-guide/examples.html#standalone-usage[Examples] section for usage and configuration.


== User Guide

If you have any questions regarding configuration of Camunda BPM Feign please
have a look at our link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/user-guide/index.html[User Guide].

== Direct usage of feign clients

You can also just use the generated feign clients directly and not via the Camunda services.
If you're interested have a look at the link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/user-guide/examples.html#usage-of-feign-clients[Examples] section for usage and configuration.

== License

This library is developed under Apache License 2.

== Contribution

If you want to contribute to this project, feel free to do so. Start with link:https://camunda-community-hub.github.io/camunda-platform-7-rest-client-spring-boot/snapshot/developer-guide/contribution.html[Contributing guide].

== Maintainer

* link:https://github.com/zambrovski[Simon Zambrovski, Holisticon AG]
* link:https://github.com/rohwerj[Jan Rohwer, Holisticon AG]
